FROM caddy:2 as caddy

FROM node:lts-buster-slim

COPY --from=caddy /usr/bin/caddy /usr/bin/
COPY --chown=node:node ./rootfs /

RUN . /build.sh && \
    rm -rf /build.sh

ENTRYPOINT ["/entrypoint.sh"]
