name: Build LTS

on:
  push:
    branches:
      - master
  pull_request:
    # The branches below must be a subset of the branches above
    branches:
      - master

permissions:
  contents: read
  packages: write

jobs:
  build:
    uses: ./.github/workflows/build-image.yml
    with:
      node-version: lts
      tag: lts
      cache-scope: lts
